# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fF8PPCBaIYjOhJj57Udlgjv4XCMUhDeQ
"""

import streamlit as st

# Title of the app
st.title("Personalized Age and Name App")

# User input for name
name = st.text_input("What's your name?")

# User input for age
age = st.slider("How old are you?", 0, 100, 25)  # Default age set to 25

# Function to determine life stage
def get_life_stage(age):
    if age < 13:
        return "You're a child!"
    elif 13 <= age < 20:
        return "You're a teenager!"
    elif 20 <= age < 30:
        return "You're a young adult!"
    elif 30 <= age < 65:
        return "You're an adult!"
    else:
        return "You're a senior!"

# Display the personalized message if both fields are filled
if name:
    life_stage = get_life_stage(age)
    st.write(f"Hello, {name}!")
    st.write(f"You are {age} years old. {life_stage}")

# Additional feature: Show a motivational quote
if st.button("Get a Motivational Quote"):
    quotes = [
        "Believe you can and you're halfway there.",
        "Act as if what you do makes a difference. It does.",
        "Success is not the key to happiness. Happiness is the key to success.",
        "The only way to do great work is to love what you do.",
    ]
    st.write(random.choice(quotes))